notifications:
  slack:
    secure: ZaeRnZLbnqMqFoH10X6U9ylAM4f9Up3ebgA097FVy71VD8hjMiw3lYZb7p/WxxsaQAplOykLQ8PUeuV7rOhotzT23xYijh3TpDrmxs+TnZ6HhHnILvV85YNfLyrvniPb6kHQHVcMTDPvIVqR9MP6gZqxZlnpqUttzYgr2rCv0vl98XE/TeY+IRUldsGEdZ84WTrWsNCb/LqCyM3+FJCHaXRZcmokHJsdStZNWpC4S9MfiDzd9DzH4pg4PT4xKLIRCtguhxnc/or56LYCnTV4PRRk4rdVaHOHRoN/0EGKOG9eWTInhDY33me7cCEAtqGsngBzpehQXDfd7YI6lnWriGpYRk+BmZaRrcuA40QEQa5z0WoHA/m7ev+3S6PGniI+ZZg2OuAw2gUgRIHfqwQ/oVREvVzR0HM9yia5JkyH9y6HtbCB9GBpt8mB+kIWQ8BIhk4sdHnKbUuEumjr9msnLQwqpI4jLoN0Ap+ZNnwoK8Lzjf/qGlcSsmkCQ2H3aI0s+q7mqHg9ZqDn0cph8qAkdCpnedHYk/itK/tPssN0O9jgOgqseVV8p2BWxR39LnHEE9F1ghTtHuW1wmBfokEa9JD6OraG/jG3Og9lqulnsNNk3bHf4digrVaHKQkprI0jeAfO0QcyuMGuAsvuY++CwzVC7SjRf02S555E9jFqnek=

language: python
python:
  - "2.7"
  - "3.5"

env:
  - NUMPY_VERSION="==1.9.0"
  - NUMPY_VERSION=">=1.10"

matrix:
  exclude:
  - python: "3.5"
  include:
  - python: "3.5"
    env: NUMPY_VERSION=">=1.10"

before_install:
  - pip install -r requirements.txt
  - pip install flake8
  - pip install flake8-future-import
  - pip install --upgrade pytest
  - pip install --upgrade "numpy$NUMPY_VERSION"

install:
  - python setup.py install

script:
  - flake8 .
  - py.test tests
